source 'https://rubygems.org'
ruby "2.0.0"

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source'
gem 'emblem-rails'
gem 'haml-rails'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.0.0'
gem 'sass-rails'
gem 'uglifier'
gem 'rails_12factor'
gem 'handlebars-source'
